"""empty message

Revision ID: 625963e040f3
Revises: 
Create Date: 2023-11-08 13:01:56.265096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625963e040f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('items', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_column('items')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
