"""Add date column to Menu

Revision ID: c40901840818
Revises: 625963e040f3
Create Date: 2023-11-08 15:41:40.748064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40901840818'
down_revision = '625963e040f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_column('day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.DATE(), nullable=False))

    # ### end Alembic commands ###
